"""
make_version.py — records the git stamp in a generated `_version.py`.

Why this exists: `app_version()` in skate_db.py runs `git` in the folder next to the
script to determine which code produced an analysis (Info dialog, title tooltip,
`settings_json`). A bundled .exe has no git and no repo, so every colleague's analysis
would land in the library **without a version stamp**. The build script therefore runs
this script right before PyInstaller; `_version_from_bundle()` reads the result when
`sys.frozen` is true, and otherwise falls back to the git route.

The label format stays exactly `"2026-08-24 . 4df9ab5a"`, so analyses from the exe and
from the repo stay comparable with each other — that's why this runs the same git
commands with the same flags as `app_version()` (`--abbrev=8`, `-uno`).

The generated file is in `.gitignore`: it's a build artifact, and in the repo
environment it's never read (`_version_from_bundle()` only runs when frozen).

Usage:  python make_version.py [target_path]
        python make_version.py --show      (print only, write nothing)

That second form is for `build.bat`: Inno Setup gets the stamp as /DVersion=… and
puts it in "Apps and features". It deliberately prints **ASCII** (a period instead of
the middle dot, no space), because this goes through a for-loop in cmd.exe and across
a command line — the separator character in `label` doesn't survive the console code
page. The label in the library stays unchanged.
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_TARGET = os.path.join(HERE, "_version.py")


def _git(*args):
    """Same helper as in skate_db.py: "" on any error (no git, no repo)."""
    try:
        r = subprocess.run(["git", "-C", HERE] + list(args),
                           capture_output=True, text=True, timeout=5)
    except Exception:
        return ""
    return r.stdout.strip() if r.returncode == 0 else ""


def git_stamp():
    """(commit, date, dirty) from the repo next to this script; empty strings outside a repo."""
    commit = date = ""
    out = _git("log", "-1", "--abbrev=8", "--format=%h%x09%cs")
    if "\t" in out:
        commit, date = out.split("\t", 1)
    # Untracked files don't count as "dirty" (-uno): videos and npz's next to the code
    # say nothing about the logic that ran.
    dirty = bool(commit) and bool(_git("status", "--porcelain", "-uno"))
    return commit, date, dirty


def ascii_stamp():
    """`2026-08-25.a4be1f2b+`, or "unknown" outside a git repo. See the docstring."""
    commit, date, dirty = git_stamp()
    if not commit:
        return "unknown"
    return f"{date}.{commit}{'+' if dirty else ''}"


def write(target=DEFAULT_TARGET):
    commit, date, dirty = git_stamp()
    content = (
        '"""Generated by make_version.py — do not hand-edit, not in git."""\n'
        f'COMMIT = {commit!r}\n'
        f'DATE = {date!r}\n'
        f'DIRTY = {dirty!r}\n'
    )
    with open(target, "w", encoding="utf-8") as f:
        f.write(content)
    label = f"{date} · {commit}{'+' if dirty else ''}" if commit else "(no git stamp)"
    return target, label


if __name__ == "__main__":
    if "--show" in sys.argv[1:]:
        print(ascii_stamp())
        raise SystemExit(0)
    target = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TARGET
    path, label = write(target)
    print(f"{path}  ->  {label}")
