# -*- mode: python ; coding: utf-8 -*-
"""
skate_analysis.spec — PyInstaller recipe for the bundled app (EXE.md step 3).

Building (in .venv-yolo, Python 3.11):

    .venv-yolo\Scripts\python.exe -m PyInstaller --noconfirm --clean skate_analysis.spec

or just `build.bat`, which wraps the version stamp, copying the models, and building
the installer (step 4) around it.
Result: `dist\SkateAnalysis\SkateAnalysis.exe`.

The standalone scripts keep working unchanged; this is purely alongside them.
Everything the bundle needs was already given to the code in steps 1 and 2
(`app_dir()`/`data_dir()` and the log file in skate_environment.py) — no module gets
patched here.

Four choices that deserve an explanation:

1. **onedir, not onefile.** Onefile unpacks ~1.5 GB to %TEMP% on every start, which
   would undo the very startup work (splash screen + lazy backend import) done for
   this. Inno Setup (step 4) still packages this folder into a single download.
2. **windowed, no console.** Hence `start_log()` in skate_gui.py: without a console
   `sys.stdout` is None and the tqdm bar from ultralytics/rtmlib breaks (step 2).
3. **noupx.** UPX mangles the Qt and torch DLLs.
4. **The models are NOT included.** `yolo26x-pose.pt`, `yolo26x-pose-dml.onnx` and the
   RTMPose model land next to the exe (build.bat copies them in for testing, Inno
   installs them in step 4). `app_dir()` finds them there. Saves 557 MB of copying on
   every rebuild and lets a model be swapped without rebuilding.
"""

import os

from PyInstaller.utils.hooks import collect_data_files

HERE = os.path.abspath(SPECPATH)

# ── Included ────────────────────────────────────────────────────────────────────
# ultralytics data (bytetrack.yaml, default.cfg, ...) and the torch/onnxruntime/cv2
# DLLs are already handled by the bundled hooks. rtmlib has no hook, so we collect it
# ourselves.
datas = collect_data_files("rtmlib")

hiddenimports = [
    # The GUI only imports the backend on the first analysis (`_load_backend`), and
    # `_backend_available()` uses find_spec to check whether ultralytics/torch/rtmlib
    # are present — so all three must be in the bundle even though there's no
    # top-level import anywhere.
    "skate_yolo",
    "ultralytics",
    "torch",
    "rtmlib",
    # Generated by make_version.py; `_version_from_bundle()` in skate_db.py does
    # `import _version` inside a try, so without this line the bundle could end up
    # without a version stamp and every analysis would show "unknown" in the Info
    # dialog.
    "_version",
]

# ── Excluded ────────────────────────────────────────────────────────────────────
# This is where the savings come from: PySide6 ships every Qt module (634 MB) while
# this app uses four (QtCore, QtGui, QtWidgets, QtCharts). What isn't imported
# shouldn't end up in the bundle in principle, but matplotlib (via
# ultralytics.utils.plotting) likes to drag in Qt and tk backends; this list is the
# lock on that door.
excludes = [
    # The MediaPipe backend is deliberately not in this package: IS_YOLO is always
    # true here.
    "mediapipe",
    # Qt modules the app never touches.
    "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets", "PySide6.QtWebEngineQuick",
    "PySide6.QtQml", "PySide6.QtQuick", "PySide6.QtQuick3D", "PySide6.QtQuickControls2",
    "PySide6.QtQuickWidgets", "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets",
    "PySide6.QtSpatialAudio", "PySide6.QtDesigner", "PySide6.QtUiTools", "PySide6.QtTest",
    "PySide6.Qt3DCore", "PySide6.Qt3DRender", "PySide6.Qt3DInput", "PySide6.Qt3DLogic",
    "PySide6.Qt3DExtras", "PySide6.Qt3DAnimation", "PySide6.QtDataVisualization",
    "PySide6.QtGraphs", "PySide6.QtGraphsWidgets", "PySide6.QtBluetooth", "PySide6.QtNfc",
    "PySide6.QtPdf", "PySide6.QtPdfWidgets", "PySide6.QtTextToSpeech",
    "PySide6.QtSerialBus", "PySide6.QtSerialPort", "PySide6.QtHttpServer",
    "PySide6.QtRemoteObjects", "PySide6.QtScxml", "PySide6.QtSensors", "PySide6.QtHelp",
    "PySide6.QtLocation", "PySide6.QtPositioning", "PySide6.QtWebChannel",
    "PySide6.QtWebSockets", "PySide6.QtNetworkAuth",
    # GUI toolkits and notebook tooling that matplotlib/ultralytics can pull in.
    "tkinter", "matplotlib.backends.backend_tkagg", "matplotlib.backends.backend_webagg",
    "IPython", "jupyter", "notebook", "pytest", "PyInstaller",
    # The polars runtime is the third-largest chunk of the bundle at 177 MB and comes
    # in via ultralytics. Every polars import there sits in training, benchmark, plot
    # and dataframe-export paths ("scope for faster 'import ultralytics'"), and this
    # app only does inference. Measured with polars hard-blocked via sys.meta_path:
    # `import skate_yolo`, `_load_yolo()` (DirectML route) and then `model.track()`
    # and `model.predict()` on a frame all run fine without ever loading polars.
    "polars", "_polars_runtime_32",
    # Scientific packages that aren't installed here and have no business being
    # dragged in by an optional import.
    "scipy", "pandas", "tensorflow", "jax",
]

a = Analysis(
    ["skate_gui.py"],
    pathex=[HERE],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="SkateAnalysis",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                 # UPX mangles the Qt and torch DLLs
    console=False,             # no console: output goes to the log file (step 2)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # The icon of the exe, and therefore of every shortcut the installer (step 4)
    # creates. To replace it: overwrite skateanalysis.ico and rebuild. If the file is
    # missing, PyInstaller stops with "Unable to open icon file" — no fallback to its
    # own icon, so the .ico belongs in git (and is).
    icon=os.path.join(HERE, "skateanalysis.ico"),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="SkateAnalysis",
)
